/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from './stencil.core';
import {
  IAccountsFormValue,
} from './components/calculators/investment-guide/accounts-form/model/accounts-form-value';
import {
  IInvestmentGuideValue,
} from './components/calculators/investment-guide/model/investment-guide-value';
import {
  IGeneralFormValue,
} from './components/calculators/investment-guide/general-form/model/general-form-value';
import {
  IMortgageFormValue,
} from './components/calculators/investment-guide/mortgage-form/model/mortgage-form-value';

export namespace Components {
  interface BudgificIgAccountsForm {
    /**
    * Check mortgage account
    */
    'value': IAccountsFormValue;
  }
  interface BudgificIgCalculator {
    /**
    * The value
    */
    'value': IInvestmentGuideValue;
  }
  interface BudgificIgGeneralForm {
    /**
    * The form value
    */
    'value': IGeneralFormValue;
  }
  interface BudgificIgInfoButton {}
  interface BudgificIgInfoPopover {}
  interface BudgificIgMortgageForm {
    /**
    * The form value
    */
    'value': IMortgageFormValue;
  }
  interface BudgificIgRrspForm {
    /**
    * The reinvest tax return
    */
    'reinvestTaxReturn': boolean;
  }
  interface BudgificIgStepperItem {
    'constraint': any;
    'label': string;
    'max': number;
    'min': number;
    'step': number;
    'value': number;
  }
  interface BudgificInvestmentGuide {
    /**
    * The amount to invest
    */
    'value': IInvestmentGuideValue;
  }
  interface ResultDetails {}
  interface ResultDetailsButton {}
}

declare global {


  interface HTMLBudgificIgAccountsFormElement extends Components.BudgificIgAccountsForm, HTMLStencilElement {}
  var HTMLBudgificIgAccountsFormElement: {
    prototype: HTMLBudgificIgAccountsFormElement;
    new (): HTMLBudgificIgAccountsFormElement;
  };

  interface HTMLBudgificIgCalculatorElement extends Components.BudgificIgCalculator, HTMLStencilElement {}
  var HTMLBudgificIgCalculatorElement: {
    prototype: HTMLBudgificIgCalculatorElement;
    new (): HTMLBudgificIgCalculatorElement;
  };

  interface HTMLBudgificIgGeneralFormElement extends Components.BudgificIgGeneralForm, HTMLStencilElement {}
  var HTMLBudgificIgGeneralFormElement: {
    prototype: HTMLBudgificIgGeneralFormElement;
    new (): HTMLBudgificIgGeneralFormElement;
  };

  interface HTMLBudgificIgInfoButtonElement extends Components.BudgificIgInfoButton, HTMLStencilElement {}
  var HTMLBudgificIgInfoButtonElement: {
    prototype: HTMLBudgificIgInfoButtonElement;
    new (): HTMLBudgificIgInfoButtonElement;
  };

  interface HTMLBudgificIgInfoPopoverElement extends Components.BudgificIgInfoPopover, HTMLStencilElement {}
  var HTMLBudgificIgInfoPopoverElement: {
    prototype: HTMLBudgificIgInfoPopoverElement;
    new (): HTMLBudgificIgInfoPopoverElement;
  };

  interface HTMLBudgificIgMortgageFormElement extends Components.BudgificIgMortgageForm, HTMLStencilElement {}
  var HTMLBudgificIgMortgageFormElement: {
    prototype: HTMLBudgificIgMortgageFormElement;
    new (): HTMLBudgificIgMortgageFormElement;
  };

  interface HTMLBudgificIgRrspFormElement extends Components.BudgificIgRrspForm, HTMLStencilElement {}
  var HTMLBudgificIgRrspFormElement: {
    prototype: HTMLBudgificIgRrspFormElement;
    new (): HTMLBudgificIgRrspFormElement;
  };

  interface HTMLBudgificIgStepperItemElement extends Components.BudgificIgStepperItem, HTMLStencilElement {}
  var HTMLBudgificIgStepperItemElement: {
    prototype: HTMLBudgificIgStepperItemElement;
    new (): HTMLBudgificIgStepperItemElement;
  };

  interface HTMLBudgificInvestmentGuideElement extends Components.BudgificInvestmentGuide, HTMLStencilElement {}
  var HTMLBudgificInvestmentGuideElement: {
    prototype: HTMLBudgificInvestmentGuideElement;
    new (): HTMLBudgificInvestmentGuideElement;
  };

  interface HTMLResultDetailsElement extends Components.ResultDetails, HTMLStencilElement {}
  var HTMLResultDetailsElement: {
    prototype: HTMLResultDetailsElement;
    new (): HTMLResultDetailsElement;
  };

  interface HTMLResultDetailsButtonElement extends Components.ResultDetailsButton, HTMLStencilElement {}
  var HTMLResultDetailsButtonElement: {
    prototype: HTMLResultDetailsButtonElement;
    new (): HTMLResultDetailsButtonElement;
  };
  interface HTMLElementTagNameMap {
    'budgific-ig-accounts-form': HTMLBudgificIgAccountsFormElement;
    'budgific-ig-calculator': HTMLBudgificIgCalculatorElement;
    'budgific-ig-general-form': HTMLBudgificIgGeneralFormElement;
    'budgific-ig-info-button': HTMLBudgificIgInfoButtonElement;
    'budgific-ig-info-popover': HTMLBudgificIgInfoPopoverElement;
    'budgific-ig-mortgage-form': HTMLBudgificIgMortgageFormElement;
    'budgific-ig-rrsp-form': HTMLBudgificIgRrspFormElement;
    'budgific-ig-stepper-item': HTMLBudgificIgStepperItemElement;
    'budgific-investment-guide': HTMLBudgificInvestmentGuideElement;
    'result-details': HTMLResultDetailsElement;
    'result-details-button': HTMLResultDetailsButtonElement;
  }
}

declare namespace LocalJSX {
  interface BudgificIgAccountsForm {
    'onValueChanged'?: (event: CustomEvent<any>) => void;
    /**
    * Check mortgage account
    */
    'value'?: IAccountsFormValue;
  }
  interface BudgificIgCalculator {
    'onConfigClick'?: (event: CustomEvent<any>) => void;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    /**
    * The value
    */
    'value'?: IInvestmentGuideValue;
  }
  interface BudgificIgGeneralForm {
    'onValueChanged'?: (event: CustomEvent<any>) => void;
    /**
    * The form value
    */
    'value'?: IGeneralFormValue;
  }
  interface BudgificIgInfoButton {}
  interface BudgificIgInfoPopover {}
  interface BudgificIgMortgageForm {
    'onValueChanged'?: (event: CustomEvent<any>) => void;
    /**
    * The form value
    */
    'value'?: IMortgageFormValue;
  }
  interface BudgificIgRrspForm {
    'onReinvestTaxReturnChange'?: (event: CustomEvent<any>) => void;
    /**
    * The reinvest tax return
    */
    'reinvestTaxReturn'?: boolean;
  }
  interface BudgificIgStepperItem {
    'constraint'?: any;
    'label'?: string;
    'max'?: number;
    'min'?: number;
    'onValueChange'?: (event: CustomEvent<any>) => void;
    'step'?: number;
    'value'?: number;
  }
  interface BudgificInvestmentGuide {
    'onValueChange'?: (event: CustomEvent<any>) => void;
    /**
    * The amount to invest
    */
    'value'?: IInvestmentGuideValue;
  }
  interface ResultDetails {}
  interface ResultDetailsButton {}

  interface IntrinsicElements {
    'budgific-ig-accounts-form': BudgificIgAccountsForm;
    'budgific-ig-calculator': BudgificIgCalculator;
    'budgific-ig-general-form': BudgificIgGeneralForm;
    'budgific-ig-info-button': BudgificIgInfoButton;
    'budgific-ig-info-popover': BudgificIgInfoPopover;
    'budgific-ig-mortgage-form': BudgificIgMortgageForm;
    'budgific-ig-rrsp-form': BudgificIgRrspForm;
    'budgific-ig-stepper-item': BudgificIgStepperItem;
    'budgific-investment-guide': BudgificInvestmentGuide;
    'result-details': ResultDetails;
    'result-details-button': ResultDetailsButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'budgific-ig-accounts-form': LocalJSX.BudgificIgAccountsForm & JSXBase.HTMLAttributes<HTMLBudgificIgAccountsFormElement>;
      'budgific-ig-calculator': LocalJSX.BudgificIgCalculator & JSXBase.HTMLAttributes<HTMLBudgificIgCalculatorElement>;
      'budgific-ig-general-form': LocalJSX.BudgificIgGeneralForm & JSXBase.HTMLAttributes<HTMLBudgificIgGeneralFormElement>;
      'budgific-ig-info-button': LocalJSX.BudgificIgInfoButton & JSXBase.HTMLAttributes<HTMLBudgificIgInfoButtonElement>;
      'budgific-ig-info-popover': LocalJSX.BudgificIgInfoPopover & JSXBase.HTMLAttributes<HTMLBudgificIgInfoPopoverElement>;
      'budgific-ig-mortgage-form': LocalJSX.BudgificIgMortgageForm & JSXBase.HTMLAttributes<HTMLBudgificIgMortgageFormElement>;
      'budgific-ig-rrsp-form': LocalJSX.BudgificIgRrspForm & JSXBase.HTMLAttributes<HTMLBudgificIgRrspFormElement>;
      'budgific-ig-stepper-item': LocalJSX.BudgificIgStepperItem & JSXBase.HTMLAttributes<HTMLBudgificIgStepperItemElement>;
      'budgific-investment-guide': LocalJSX.BudgificInvestmentGuide & JSXBase.HTMLAttributes<HTMLBudgificInvestmentGuideElement>;
      'result-details': LocalJSX.ResultDetails & JSXBase.HTMLAttributes<HTMLResultDetailsElement>;
      'result-details-button': LocalJSX.ResultDetailsButton & JSXBase.HTMLAttributes<HTMLResultDetailsButtonElement>;
    }
  }
}


